http_port 3128
visible_hostname squid-control-center-v5

access_log stdio:T:/VM/VPN/squid/access.log
cache_log stdio:T:/VM/VPN/squid/cache.log

auth_param basic program "C:/Python311/python.exe" "T:/VM/VPN/squid/basic_db_auth.py" "T:/VM/VPN/squid/squid_manager.db"
auth_param basic realm Firmenproxy
auth_param basic credentialsttl 2 hours
auth_param basic casesensitive off
acl authenticated proxy_auth REQUIRED

external_acl_type db_acl ttl=60 negative_ttl=20 %LOGIN %SRC %URI "C:/Python311/python.exe" "T:/VM/VPN/squid/db_acl_helper.py" "T:/VM/VPN/squid/squid_manager.db"
acl db_ok external db_acl

acl localhost src 127.0.0.1/32 ::1
acl localnet src 192.168.0.0/16
acl localnet src 10.0.0.0/8
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl Safe_ports port 21
acl Safe_ports port 1025-65535
acl CONNECT method CONNECT
acl blocked_urls url_regex -i "T:/VM/VPN/squid/blocked_urls.txt"

# deny_info Vorlagen für Ersatz-Pages
# acl cat_138 url_regex -i "T:/VM/VPN/squid/blocked_urls.txt"
# deny_info T:/VM/VPN/squid/blocked_template.html cat_138
# acl cat_238 url_regex -i "T:/VM/VPN/squid/blocked_urls.txt"
# deny_info T:/VM/VPN/squid/blocked_template.html cat_238

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost
http_access deny !authenticated
http_access deny !db_ok
http_access deny blocked_urls
http_access allow localnet authenticated db_ok
http_access deny all
